### ISSUE TITLE
React 18 Support for @algolia/recommend-react

### ISSUE THREAD

**Issue by steven-hoffman-jomashop** [algolia/react-recommendations#106]
## Description
For @algolia/recommend-react

The [package.json](https://github.com/algolia/recommend/blob/v1.7.0/packages/recommend-react/package.json#L38) shows that react 18 is not supported. (Peer dependency `react": ">= 16.8.0 < 18`)

- Do you intend to support react 18?
- Will the module work with react 18?

**Comment by marialungu** [comment]
Hi, 
Thank you for your feedback, we just opened a PR in order to address this issue and soon we will perform a release.

Thank you

**Comment by francoischalifour** [comment]
Closed in #107.
