### ISSUE TITLE
I need Recommendations to fetch the Recommendations record but when i used GetRecommendationsAsync as inside that pass request i get error like {"message":"Index does not exist","status":404} i double check everything like index name and api key and permissions as well. So any solution.

### ISSUE THREAD

**Issue by mohammadaltamas** [algolia/react-recommendations#139]
var requests = new List<RecommendRequest> {
                          new RecommendRequest {
                              IndexName = l.Items[0].Name, //here is index name
                              ObjectID = "333434349435",
                              Model = "related-products",
                              Threshold = 10,
                            MaxRecommendations = 10,
                            QueryParameters = new Query(),
                            FallbackParameters = new Query()
                          }
                        };

            var recommendationClient = new RecommendClient(algApplicationId, algAdminApiKey);

            var res = client.GetApiKey(algAdminApiKey);

            if (res.Acl.Contains("recommendation"))
            {
                Console.WriteLine("ok");
            }

            try
            {
                
                var task = Task.Run(() => recommendationClient.GetRecommendationsAsync<NewsDetail>(requests));
                if (task.Wait(TimeSpan.FromSeconds(300)))
                {
                    var response = task;
                    Console.WriteLine($"ObjectID: {response}");
                }
                else
                {
                    throw new Exception("Request Timed out");
                }
            }
            catch (AggregateException ex)
            {

                foreach (var inner in ex.InnerExceptions)
                {
                    Console.WriteLine(inner.Message);
                }

            }

**Comment by mohammadaltamas** [comment]
i am done this code in .net core 6

**Comment by raed667** [comment]
Hey @mohammadaltamas this is the repository for the Web (JavaScript & React) UI components for Algolia Recommend. 

If you have a question about the C# client please check [this documentation](https://www.algolia.com/doc/api-client/methods/recommend/?client=csharp), or open an issue on the https://github.com/algolia/algoliasearch-client-csharp repository.
