### ISSUE TITLE
useRecommendations & useRelatedProducts & useFrequentlyBoughtTogether cause infinite loop due to useEffect

### ISSUE THREAD

**Issue by benj3** [algolia/react-recommendations#49]
## Description
`useRecommendations` & `useRelatedProducts` & `useFrequentlyBoughtTogether` hooks are causing the app to infinitely loop due to the useEffect dependencies. 

## Reproduction

Very simple cra app to test reccomendations
```
import recommend from '@algolia/recommend';
import { useRecommendations } from '@algolia/recommend-react';

import './App.css';

const indexName = 'INDEX_NAME';
const recommendClient = recommend('APP_ ID', 'API_KEY');
const objectId = '99999999';

function App() {
  const { recommendations } = useRecommendations({
      model: 'related-products',
      recommendClient,
      indexName,
      objectIDs: [objectId],
  });

  console.log(recommendations);

  return (
    <div className="App">
      <h1>Testing Algolia Recommend</h1>
    </div>
  );
}

export default App;
```

**Steps**

1. Run above code with correct indices/apps
2. Application enters a full infinite loop constantly logging out recommendations.

## Expected behavior
App should load once with relevant recommendations and not infinitely loop.

## Environment

- OS: macOS
- Browser: Chrome
- Library versions:
    "@algolia/recommend": "^4.10.3",
    "@algolia/recommend-react": "^1.0.0",

## Possible Cause (We have debugged)
Currently the hooks useEffect dependency is reliant on the props object this object contains the `status` prop which is also set within the useEffect thus causing an infinite loop.

**Comment by shortcuts** [comment]
Hi @benj3,

Thanks for reporting this issue.

It seems that the refs of the variables passed to the `use*` hooks changes at every render, causing an infinite loop `useEffect` due of the `props` dependency.

The following implementation solves this issue, but we will find a more user friendly way to handle this!
```js
  const props = React.useMemo(
    () => ({
      model: 'related-products',
      recommendClient,
      indexName,
      objectIDs: [objectID],
    }),
    []
  );

  const { recommendations } = useRecommendations(props);
``` 

(With the snippet in the your reproduction, you don't need to pass `objectID` etc. to the `useMemo` dependency, but it will be needed if the variables are in the `App` component itself.)

**Comment by tkrugg** [comment]
This comes from the fact that the [underlying implem uses `useEffect` watching `prop`](https://github.com/algolia/recommend/blob/next/packages/recommend-react/src/useRecommendations.ts#L27), which indeed points to a new reference at each render of the parent component. Here is a simpler example illustrating the issue: https://codesandbox.io/s/thirsty-edison-7owvj?file=/src/App.js:143-168

Replacing `[prop]` by `[prop.model, prop.indexName, objectIDs.join()]` should fix it. (You can skip the client)

By the way, why are we putting `setStatus ` in the `useEffect` deps? Functionally we only need to re-fetch recommendation every time one of the prop changes?

**Comment by laurencestokes** [comment]
@shortcuts Thanks for that!  I've tried the solution you posted (with useRelatedProducts) and that works. I can put a comment in the code for now explaining why it's like that (and it's in beta at the moment so that's understandable).

**Comment by benj3** [comment]
Yes I came to the same conclusion @tkrugg when investigating the cause thanks for taking a look. 

We will use the memo example for the time being and update when a fix has been pushed out. 

Cheers

**Comment by shortcuts** [comment]
Hey @benj3,

The fix has been released in the `v1.1.0` version, you should now be able to use the hooks normally :D

Feel free to let us know if you see any other issue!

**Comment by dushakov92** [comment]
@shortcuts 
I am encountering the same issue with `"@algolia/recommend-react": "^1.14.0"`

```javascript
import recommend from '@algolia/recommend';
import { useRelatedProducts } from '@algolia/recommend-react';

// Create a new instance of the algolia recommend client.
const recommendClient = recommend(algoliaAppID, algoliaSearchKey)

 // Fetch related items.
const {recommendations} = useRelatedProducts({
    recommendClient,
    indexName: algoliaIndexName,
    objectIDs: [objectID],
    maxRecommendations: 3,
    threshold: 25
})

console.log(recommendations)
```

Result:
![infinite-loop](https://github.com/algolia/recommend/assets/69015238/09e36896-bd2a-46fa-aa0b-1e1524cd694f)

**Comment by dushakov92** [comment]
> Hi @benj3,
> 
> Thanks for reporting this issue.
> 
> It seems that the refs of the variables passed to the `use*` hooks changes at every render, causing an infinite loop `useEffect` due of the `props` dependency.
> 
> The following implementation solves this issue, but we will find a more user friendly way to handle this!
> 
> ```js
>   const props = React.useMemo(
>     () => ({
>       model: 'related-products',
>       recommendClient,
>       indexName,
>       objectIDs: [objectID],
>     }),
>     []
>   );
> 
>   const { recommendations } = useRecommendations(props);
> ```
> 
> (With the snippet in the your reproduction, you don't need to pass `objectID` etc. to the `useMemo` dependency, but it will be needed if the variables are in the `App` component itself.)

@shortcuts 
i will add that your `useMemo()` solution does work.
