### ISSUE TITLE
Module '"@algolia/recommend-react"' has no exported member 'useTrendingItems'

### ISSUE THREAD

**Issue by brzomar** [algolia/react-recommendations#96]
## Description

File : packages/recommend-react/src/index.ts
Missing export : `export * from './useTrendingItems';`

## Environment

- OS: [Windows / Linux / macOS / iOS / Android]
- Browser: [Chrome, Safari...]
- Library version: [1.5.0]

**Comment by marialungu** [comment]
hi, the export was added and it's available with version 1.6.0
