### ISSUE TITLE
Can't import the named export 'dequal' (imported as 'dequal') from default-exporting module

### ISSUE THREAD

**Issue by chetan-snackmagic** [algolia/react-recommendations#99]
## Description

Getting Error in /@algolia/recommend-react/dist/esm/useStableValue.js file

Can't import the named export 'dequal' (imported as 'dequal') from default-exporting module (only default export is available)
## Reproduction

[**Preview →**](https://codesandbox.io/s/github/algolia/recommend/tree/next/examples/js-demo?file=/app.js)

**Steps**

1. Click on `...`
2. See error

## Environment

- OS: [e.g., Windows / Linux / macOS / iOS / Android]
- Browser: [e.g., Chrome, Safari]
- Library version: [e.g., 1.0.0]

**Comment by raed667** [comment]
Thank you for raising this issue @chetan-snackmagic. Do you still experience this problem with the latest version of the library?
